# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Self

steps:
- script: dir
  workingDirectory: $(Pipeline.Workspace) 
  displayName: List contents of a folder
  
- script: 
    npm config set registry https://registry.npmjs.org/
    npm config set strict-ssl false
  displayName: 'npm set registry and proxy'

- script: |
    npm install
  displayName: 'npm install'

- script: 
    npm run test
  displayName: 'Run Cucumber Test'


